name = "fataplus-nuxt-worker"
main = "./dist/_worker.js"
compatibility_date = "2024-06-01"

# Uncomment and set your account_id if deploying directly via Wrangler CLI
account_id = "f30dd0d409679ae65e841302cc0caa8c"

# If you need to specify routes or other settings, add them below as needed

[pages_build]
# Set the directory to publish
dir = ".output/public"
# Set the command to build your project
command = "npm run build"